### ISSUE TITLE
Module loads to wrong namespace

### ISSUE THREAD

**Issue by eplaut** [getslash/slash#532] opened 2017-03-01 12:17 UTC
Moved from vmalloc/dessert#2
Created repository to reproduce at [eplaut/dessert_test](https://github.com/eplaut/dessert_test)

I made many variation of the test. The issue happens _only_ on `test_7.py` where the fixture taken from the root `slashconf.py` file (since there is no "local" slashconf.py) and `import config` done as absolute import, as opposed to `test_8.py` which use relative import.

`slash run . -v` output: https://github.com/eplaut/dessert_test/blob/master/output

note that I added to some `__init__.py`:
```
import sys, os
sys.path.append(os.path.dirname(os.path.dirname(__file__)))
```
to ensure the absolute import works in each tests "suite".

Also, I removed the usage of imported fixtures (except for `test_6`) to make sure it doesn't caused the issue here

Many thanks!

**Comment by vmalloc** [comment] 2017-03-01 20:28
Thanks! will look into this

**Comment by vmalloc** [comment] 2017-03-01 20:33
@eplaut This is what I'm getting when I run the reproducing suite:
![Reproducing](https://i.imgur.com/z0zfKnh.png)

This is the expected behavior as far as I understand. Am I missing something?

**Comment by eplaut** [comment] 2017-03-01 20:38
my bad. i had to clirift. the issue is not the dessert's inspection, but the outcome of loading module twice, where the fixture and test are not working on the same "copy".

the expected behavior is all tests pass. all tests check that the fixture set the config to False.

on test_7 the fixture and test are pointing to different `config` module, causing the failure.

**Comment by vmalloc** [comment] 2017-03-01 20:51
Ooooh I understand.

This is actually by design. 

Python doesn't really have a "load module by filename" feature, and what Slash (via `emport`) does is try to mimic this desired behavior. When a filename needs to be loaded, Slash deduces a module name for it. If it's a part of a package that eventually resides somewhere in `sys.path`, then a "real" name will be generated, where the root element is the uppermost package which is directly under `sys.path` somewhere.

*HOWEVER*, if the file resides in a place outside the reach of `sys.path`, Slash has to pretend it is a part of an already existing package, or in other words pretend it was magically loaded already. This is why it prepends a prefix to it so that it won't collide with another package of the same name which was loaded by mistake from a different location (think of what happens when you have several places, all named `tests`).

This works for most cases, but fails when you modify `sys.path` after the tests are loaded. In that case, Python kicks in and properly identifies your modules as local ones, and then loads them as different ones due to the fact that they're not a part of `_0` or others.

There is no easy way to solve this in Slash itself - `py.test`, for instance, completely ignores this issue and thus does not really allow you to do relative imports from the root.

The solution is to tweak your `sys.path` very early (through `.slashrc` in your project, preferably, or even in your host's environment). This way Slash is supposed to properly detect your paths without the `_0` magic at all.

**Comment by eplaut** [comment] 2017-03-01 20:56
I can't check it right now, but if I recall correctly , same behavior was when using `PYTHONPATH=$PWD slash run .` after removing all sys.path.append lines

**Comment by vmalloc** [comment] 2017-03-02 06:35
Please check and if it's indeed the case I'll look into it

**Comment by eplaut** [comment] 2017-03-02 08:43
Hi!

I ran the tests again without `sys.path.append(os.path.dirname(os.path.dirname(__file__)))` and with `PYTHONPATH=$PWD` and got the same results.

I have pushed the changes to the test repo.

Thanks!

**Comment by eplaut** [comment] 2017-03-02 09:01
BTW, adding `sys.path.append(os.getcwd())` to `.slachrc`, raises an error `ImportError: No module named config`

**Comment by vmalloc** [comment] 2017-03-22 15:26
@eplaut Finally got around to examine this more closely.

The problem is that the `import config` syntax in Python is deprecated for modules inside the packages. This is why `from __future__ import absolute_import` exists. Your files are importing `config` as if it is a module in `sys.path`, which it isn't - they should use `from .. import config` to stay consistent with the rest of the package...

**Comment by vmalloc** [comment] 2017-03-28 06:17
@eplaut ?

**Comment by vmalloc** [comment] 2017-04-02 05:47
Closing this unless there's any new input to be provided.

**Closed by vmalloc** 2017-04-02 05:47 UTC
Labels: Status: In Progress
