### ISSUE TITLE
Add basic logic for excluding multiple parameters

### ISSUE THREAD

**Issue by alona11** [getslash/slash#659] opened 2017-08-14 08:11 UTC
Currently, the exclude function allows excluding values of a single parameters (e.g exclude param1 when param1 in [x,y].
It would be helpful if the user could define logic for combining multiple parameters to exclude. For example: exclude when param1==y AND param2=x, and so forth.

**Comment by vmalloc** [comment] 2018-06-19 08:03
Duplicate of #528

**Closed by vmalloc** 2018-06-19 08:03 UTC
