### ISSUE TITLE
slash.requires on derived classes gets applied to all derivatives

### ISSUE THREAD

**Issue by uartie** [getslash/slash#928] opened 2019-03-07 23:07 UTC
Why does DerivedATest requirement cause DerivedBTest to inherit the requirement?  Am I missing something?

```
# file testme.py
import slash

@slash.requires(lambda: True)
class BaseTest(slash.Test):
  def common(self):
    pass

@slash.requires(lambda: False, "DerivedATest Requirement Unmet")
class DerivedATest(BaseTest):
  def test(self):
    self.common()

class DerivedBTest(BaseTest):
  def test(self):
    self.common()
```

```
$ slash run testme.py -v
2 tests collected   
[2019-03-07 22:55:30] #1: testme.py:DerivedATest.test
Skipped: Unmet requirement: DerivedATest Requirement Unmet, Test: <testme.py:DerivedATest.test>
[2019-03-07 22:55:30] #2: testme.py:DerivedBTest.test
Skipped: Unmet requirement: DerivedATest Requirement Unmet, Test: <testme.py:DerivedBTest.test>
```

**Comment by vmalloc** [comment] 2019-03-08 12:20
Slash uses the class derivation logic to its full extent - meaning that a test class B that derives from A *extends A*, meaning that everything that applies to class A apples for B as well.

Marking requirements at the class level applies for the class itself, and therefore it is implied that child classes inherit those requirements.

You have two choices if this is inconvenient to you:
1. Move to use function tests, which allow a finer grained control over composition and requirements of fixtures
2. Decorate individual methods with the desired requirements (possibly through a utility decorator if it becomes too verbose).

Hope that clears up things a bit

**Comment by uartie** [comment] 2019-03-08 20:03
Yes, I understand that "slash.requires" defined at the base class will be inherited by all the derived classes.  I would expect that.

The problem is that DerivedBTest inherited DerivedATest's "slash.requires".

Maybe I should have wrote:
```
class BaseTest(slash.Test):
  def common(self):
    pass

@slash.requires(lambda: False, "DerivedATest Requirement Unmet")
class DerivedATest(BaseTest):
  def test(self):
    self.common()

class DerivedBTest(BaseTest):
  def test(self):
    self.common()
```
...which produces the same output results as described.

**Comment by vmalloc** [comment] 2019-03-09 19:19
@uartie I'm not sure I'm following you - running the latest example you wrote seems to work as expected on my end:
```
2 tests collected
[2019-03-09 19:18:45] #1: /tmp/slash_tests/test_something.py:DerivedATest.test
Skipped: Unmet requirement: DerivedATest Requirement Unmet, Test: </tmp/slash_tests/test_something.py:DerivedATest.test>
[2019-03-09 19:18:45] #2: /tmp/slash_tests/test_something.py:DerivedBTest.test
```
As you can see the second test runs fine, while the first is skipped, as expected

**Comment by uartie** [comment] 2019-03-11 19:19
Ha, you are right... my latest example does work.

So why doesn't the first example work?  That is, adding slash.requires to the base class (which evaluates to True, btw) is causing the derived class explicit slash.requires to propagate/leak to the other derived classes.

**Comment by vmalloc** [comment] 2019-03-11 20:57
@uartie oh now I see what you mean - I missed it reading it for the first time, sorry!
Yes, it reproduces on my end. Will check and have a fix ready ASAP. Thanks for reporting!

**Comment by vmalloc** [comment] 2019-03-12 08:36
@uartie I pushed a fix that will get merged to `develop` soon. Would appreciate if you can test it and make sure it works well for you.

**Comment by vmalloc** [comment] 2019-03-12 14:53
I reverted the original fix due to a regression we're investigating. Will push a proper fix soon

**Closed** 2019-03-13 07:12 UTC
Labels: C-bug, S-in-progress
